import csv
import datetime
import httpx
import json
import time
from datetime import datetime
from pathlib import Path
from http_tesis import cached_get

"""
This file gets tesis (legal precedents) most recent information from the Supreme
Court's API. This information will only be accessed for tesis emitted after 
July 2025, since everything before that has been provided via csv file. Because
tesis are given progressive id's, we know which is the last historical id we have.
This number is written as a global variable for the code.

"""

BASE_DIR = Path(__file__).parent.parent.parent.parent

DATA_DIR = BASE_DIR / "data"
RAW_DATA = DATA_DIR / "raw_data"
TESIS_DIR = RAW_DATA / "tesis_data"

HISTORICAL_TESIS = 2030777

TESIS_CSV_COLUMNS = (
    "huellaDigital",
    "idTesis",
    "epoca",
    "localizacion",
    "anio",
    "mes",
    "instancia",
    "organoJuris",
    "fuente",
    "materias",
    "tipoTesis",
    "tesis",
    "rubro",
    "texto",
    "precedentes",
    "notaPublica",
    "anexos",
    "fuenteExtraccion",
)


def build_tesis_csv():
    """
    Create a CSV file populated with columns corresponding to the keys in each
    tesis (json structure). This file will integrate all tesis generated since
    August 2025 that will be accessed through the Supreme Court's API.

    Because tesis can be generated by courts different than the Supreme Court,
    we will generate two lists from the outset in order to save the corresponding
    information (one general and one specific to the Supreme Court)

    Inputs:
        None

    Returns:
        None. Creates csv files for Supreme Court and general tesis information
    """

    # Access all data from API. Both general and specific to the Supreme Court
    general_tesis, general_tesis_scjn = get_all_tesis()

    # Create general csv
    output_filename_general = "tesis_data_api.csv"
    with open(TESIS_DIR / output_filename_general, "w") as f:
        writer = csv.DictWriter(f, fieldnames=TESIS_CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(general_tesis)

    # Create csv specific to the Supreme Court
    output_filename_scjn = "tesis_data_api_scjn.csv"
    with open(TESIS_DIR / output_filename_scjn, "w") as f:
        writer = csv.DictWriter(f, fieldnames=TESIS_CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(general_tesis_scjn)

    return general_tesis


def get_all_tesis():
    """

    Given the base url for the API and type of API we are accessing ('tesis'),
    this function generates a list of dictionaries, each one containing information
    of a specific tesis.

    This function loops over lists of ids accessed through the API.

    Inputs:
        url (str): base URL for API request

    Outputs:
        general_tesis (list of dics): list of dictionaries of tesis.
        general_tesis_scjn (list of dics): list containing dictionaries of tesis
        specific to the Supreme Court.
    """

    general_tesis = []
    general_tesis_scjn = []

    # We will begin our loop in the first page of the API
    page_number = 0

    while page_number is not None:
        tesis_data_general, tesis_data_scjn, page_number = get_id_list(page_number)
        general_tesis.extend(tesis_data_general)
        general_tesis_scjn.extend(tesis_data_scjn)
        if page_number is None:
            break
        page_number += 1

    return general_tesis, general_tesis_scjn


def get_id_list(page_number):
    """

    Given the base url for the API and type of API we are accessing ('tesis'),
    this function will access a list of ids to loop through and access each
    individual element to extract all information from a given tesis.

    Inputs:
        url (str): base URL for API request
        page_number (int): page number of id page we are accessing in the API

    Outputs:
        general_tesis (list of dics): list of dictionaries of tesis.
        general_tesis_scjn (list of dics): list containing dictionaries of tesis
        specific to the Supreme Court.
        page_number (str): will return None if we have reached a tesis that we
        already know is in the historical dataset, which means we can stop
        accessing past information from the API.
    """

    tesis_data_general = []
    tesis_data_scjn = []

    # The first page (0) doesn't include a parameter of looping over pages
    if page_number == 0:
        id_list = cached_get("ids")
    else:
        kwargs = {"page": str(page_number)}
        id_list = cached_get("ids", **kwargs)

    for id_record in id_list:
        # Check if we have reached records that we already have in historical
        if int(id_record) <= HISTORICAL_TESIS:
            page_number = None
            break
        response = cached_get(id_record)
        # Add source of extraction to know we obtained it from API
        response["fuenteExtraccion"] = "api"
        # Add tesis if it comes from the Supreme Court
        if response["instancia"] == "Suprema Corte de Justicia de la Nación":
            tesis_data_scjn.append(response)
        # Add all tesis to the list
        tesis_data_general.append(response)

    return tesis_data_general, tesis_data_scjn, page_number


if __name__ == "__main__":
    build_tesis_csv()
