import csv
import datetime
import httpx
import json
import time
from datetime import datetime
from pathlib import Path
from http_tesis import cached_get
# from .http_scjn import cached_get

BASE_DIR = Path(__file__).parent

TESIS_DIR = BASE_DIR / "tesis_data"
JSON_TESIS_DIR = TESIS_DIR / "_cache"

JSON_TESIS_DIR_A = JSON_TESIS_DIR / "_tesis_json_api"
if not JSON_TESIS_DIR_A.is_dir():
    JSON_TESIS_DIR_A.mkdir(parents=True, exist_ok=True)

BASE_URL = "https://bicentenario.scjn.gob.mx/repositorio-scjn/api/v1/"
HISTORICAL_TESIS = 2030777

TESIS_CSV_COLUMNS = (
    "huellaDigital",
    "idTesis",
    "epoca",
    "localizacion",
    "anio",
    "mes",
    "instancia",
    "organoJuris",
    "fuente",
    "materias",
    "tipoTesis",
    "tesis",
    "rubro",
    "texto",
    "precedentes",
    "notaPublica",
    "anexos",
    "fuenteExtraccion",
)


def build_tesis_csv():
    """
    Create a CSV file populated with columns corresponding to the keys in each
    tesis (json structure). This file will integrate all tesis generated since
    August 2025 that will be accessed through the Supreme Court's API.

    Because tesis can be generated by courts different than the Supreme Court,
    we will generate two lists from the outset in order to save the corresponding
    information (one general and one specific to the Supreme Court)
    """

    api_type = "tesis"
    output_filename_general = "tesis_data_api.csv"

    # Access all data from API. Both general and specific to the Supreme Court
    general_tesis, general_tesis_scjn = get_all_tesis(BASE_URL, api_type)

    # Create general csv
    with open(TESIS_DIR / output_filename_general, "w") as f:
        writer = csv.DictWriter(f, fieldnames=TESIS_CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(general_tesis)

    # Create csv specific to the Supreme Court
    output_filename_scjn = "tesis_data_api_scjn.csv"
    with open(TESIS_DIR / output_filename_scjn, "w") as f:
        writer = csv.DictWriter(f, fieldnames=TESIS_CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(general_tesis_scjn)


def get_all_tesis(url, api_type):
    """

    Given the base url for the API and type of API we are accessing ('tesis'),
    this function generates a list of dictionaries, each one containing information
    of a specific tesis.

    This function loops over lists of ids accessed through the API.

    Inputs:
        url (str): base URL for API request
        api_type (str): type of information we are accessing ('tesis' or 'engroses')

    Outputs:
        general_tesis (list of dics): list of dictionaries of tesis.
        general_tesis_scjn (list of dics): list containing dictionaries of tesis
        specific to the Supreme Court.
    """

    general_tesis = []
    general_tesis_scjn = []

    # We will begin our loop in the first page of the API
    page_number = 0

    while page_number is not None:
        tesis_data_general, tesis_data_scjn, page_number = get_id_list(
            BASE_URL, api_type, page_number
        )
        general_tesis.extend(tesis_data_general)
        general_tesis_scjn.extend(tesis_data_scjn)
        if page_number is None:
            break
        page_number += 1

    return general_tesis, general_tesis_scjn


def get_id_list(url, api_type, page_number):
    """

    Given the base url for the API and type of API we are accessing ('tesis'),
    this function will access a list of ids to loop through and access each
    individual element to extract all information from a given tesis.

    Inputs:
        url (str): base URL for API request
        api_type (str): type of information we are accessing ('tesis' or 'engroses')
        page_number (int): page number of id page we are accessing in the API

    Outputs:
        general_tesis (list of dics): list of dictionaries of tesis.
        general_tesis_scjn (list of dics): list containing dictionaries of tesis
        specific to the Supreme Court.
        page_number (str): will return None if we have reached a tesis that we
        already know is in the historical dataset, which means we can stop
        accessing past information from the API.
    """

    tesis_data_general = []
    tesis_data_scjn = []

    # The first page (0) doesn't include a parameter of looping over pages
    if page_number == 0:
        id_list = cached_get(api_type, "ids")
    else:
        kwargs = {"page": str(page_number)}
        id_list = cached_get(api_type, "ids", **kwargs)

    for id_record in id_list:
        # Check if we have reached records that we already have in historical
        if int(id_record) <= HISTORICAL_TESIS:
            page_number = None
            break
        response = cached_get(api_type, id_record)
        # Add source of extraction to know we obtained it from API
        response["fuenteExtraccion"] = "api"

        # Add tesis if it comes from the Supreme Court
        if response["instancia"] == "Suprema Corte de Justicia de la Nación":
            tesis_data_scjn.append(response)
        # Add all tesis to the list
        tesis_data_general.append(response)

    return tesis_data_general, tesis_data_scjn, page_number
