"""
ngrams_solicitudes.py
This file is a basic, raw ngrams counter,
it uses raw frequency vs the salient_tokens_solicitudes.py
file that does saliency comparison.
This was the first ngrams file we did, but opted to use the salient_tokens
analysis for our visualizations
"""

import csv
import argparse
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = (
    ROOT / "data" / "clean_data" / "solicitudes" / "clean_solicitudes_2017_2026.csv"
)

STOPWORDS = {
    "el",
    "la",
    "los",
    "las",
    "un",
    "una",
    "unos",
    "unas",
    "y",
    "o",
    "u",
    "e",
    "de",
    "del",
    "al",
    "a",
    "en",
    "por",
    "denominadopara",
    "con",
    "sin",
    "sobre",
    "que",
    "como",
    "cuando",
    "donde",
    "cada",
    "uno",
    "este",
    "esta",
    "quien",
    "se",
    "su",
    "sus",
    "mi",
    "mis",
    "me",
    "te",
    "le",
    "les",
    "lo",
    "nos",
    "no",
    "sí",
    "si",
    "ya",
    "más",
    "menos",
    "muy",
    "tan",
    "también",
    "tampoco",
    "todo",
    "toda",
    "todos",
    "todas",
    "mismo",
    "misma",
    "así",
    "asi",
    "vez",
    "día",
    "dia",
    "año",
    "ano",
    "parte",
    "partes",
    "estos",
    "estas",
    "esos",
    "esas",
    "aquello",
    "aquella",
    "enero",
    "febrero",
    "marzo",
    "abril",
    "mayo",
    "junio",
    "julio",
    "agosto",
    "septiembre",
    "octubre",
    "noviembre",
    "diciembre",
    "mes",
    "meses",
    "periodo",
    "lapso",
    "comprendido",
    "durante",
    "actual",
    "pasado",
    "presente",
    "fecha",
    "fechas",
    "http",
    "https",
    "www",
    "com",
    "mx",
    "html",
    "php",
    "aspx",
    "url",
    "sitio",
    "web",
    "enlace",
    "link",
    "archivo",
    "pdf",
    "formatos",
    "imagen",
    "jpg",
    "png",
    "clic",
    "click",
    "adjunto",
    "adjunta",
    "anexo",
    "anexa",
    "descargar",
    "solicitud",
    "solicito",
    "solicita",
    "solicitante",
    "información",
    "informacion",
    "pública",
    "publica",
    "favor",
    "pudieran",
    "ser",
    "ha",
    "he",
    "fue",
    "son",
    "es",
    "unir",
    "hacer",
    "solicitar",
    "atentamente",
    "cordial",
    "saludo",
    "gracias",
    "trasparencia",
    "unidad",
    "acceso",
    "folio",
    "respuesta",
    "oficio",
    "escrito",
    "presentado",
    "mediante",
    "través",
    "traves",
    "medio",
    "proporcione",
    "entregue",
    "haga",
    "llegar",
    "pueda",
    "dar",
    "conocer",
    "copia",
    "copias",
    "versión",
    "version",
    "pública",
    "publica",
    "documento",
    "documentos",
    "expediente",
    "número",
    "numero",
    "registrado",
    "ingresado",
    "scjn",
    "suprema",
    "corte",
    "justicia",
    "nación",
    "nacion",
    "poder",
    "judicial",
    "federal",
    "ley",
    "artículo",
    "articulo",
    "art",
    "fracción",
    "fraccion",
    "inciso",
    "párrafo",
    "parrafo",
    "tesis",
    "jurisprudencia",
    "rubro",
    "sentencia",
    "ejecutoria",
    "amparo",
    "directo",
    "indirecto",
    "revisión",
    "revision",
    "sala",
    "tribunal",
    "colegiado",
    "circuito",
    "asunto",
    "asuntos",
    "acuerdo",
    "resolución",
    "resolucion",
    "votos",
    "voto",
    "ponente",
    "ministro",
    "ministra",
    "secretario",
    "actuaria",
    "[…]",
    "[...]",
    "...",
    "….",
    "señala",
    "señalada",
    "senala",
    "senalada",
    "punto",
    "puntos",
    "inciso",
    "literal",
    "referencia",
    "relación",
    "relacion",
    "respecto",
    "dicho",
    "dicha",
    "mencionada",
    "citada",
    "tal",
    "tales",
    "sujeto",
    "obligado",
    "tiene",
    "tienen",
    "ser",
    "son",
    "fue",
    "don",
    "lic",
    "está",
    "esta",
    "mexicanos",
    "mexicano",
    "mexicana",
    "peso",
    "pesos",
    "dinero",
    "adquirido",
    "adquiridos",
    "adquisicion",
    "cual",
    "cuales",
    "quiere",
    "quisiera",
    "tipo",
    "materia",
    "versaron",
    "pertenecientes",
    "dictada",
    "respectiva",
    "fueron",
    "quien",
    "presenta",
    "anexo",
    "ejercicio",
    "posible",
    "incluyendo",
    "hayan",
    "sea",
    "manera",
    "tambien",
    "debidamente",
    "caracter",
    "respetuosamente",
    "disponible",
    "mensualmente",
    "anual",
    "mas",
    "total",
    "millones",
    "mil",
    "tomo",
    "pagina",
    "paginas",
    "folio",
    "modulo",
    "tramitada",
    "derivo",
    "tratar",
    "danar",
    "otro",
    "otra",
    "otros",
    "otras",
    "aquellos",
    "aquellas",
    "general",
    "nacional",
    "social",
    "universidad",
    "directora",
    "director",
    "escuela",
    "comunicado",
    "firmado",
    "emision",
    "digital",
    "electronica",
    "fisica",
    "empresa",
    "nombre",
    "persona",
    "personas",
    "punto",
    "sentido",
    "amplio",
    "entradas",
    "salidas",
    "bienes",
    "entregado",
    "elementos",
    "causas",
    "procesos",
    "presuntos",
    "responsables",
    "irregularidades",
    "administrativas",
    "ordenadoras",
    "validez",
    "mayor",
    "autorizada",
    "juridica",
    "unifamiliar",
    "identificacion",
    "comparte",
    "adjunto",
    "www",
    "http",
    "https",
    "mx",
    "com",
    "html",
    "php",
    "url",
    "link",
    "//www",
    "proyectado",
    "el",
    "la",
    "los",
    "las",
    "un",
    "una",
    "unos",
    "unas",
    "y",
    "o",
    "u",
    "e",
    "de",
    "del",
    "al",
    "a",
    "en",
    "por",
    "para",
    "con",
    "sin",
    "sobre",
    "señor",
    "señor",
    "que",
    "como",
    "cuando",
    "donde",
    "cada",
    "uno",
    "este",
    "esta",
    "quien",
    "corresponda",
    "contradicción",
    "criterio",
    "criterios",
    "solicitud",
    "solicitar",
    "usted",
    "cordial",
    "saludo",
    "enviar",
    "ponencia",
    "ponente",
    "ministro",
    "ministra",
    "se",
    "su",
    "sus",
    "mi",
    "mis",
    "tu",
    "tus",
    "me",
    "te",
    "le",
    "les",
    "lo",
    "nos",
    "numero",
    "así",
    "asi",
    "no",
    "sí",
    "si",
    "ya",
    "más",
    "menos",
    "muy",
    "tan",
    "también",
    "tampoco",
    "toda",
    "vez",
    "dia",
    "lic",
    "pudieran",
    "solicito",
    "información",
    "informacion",
    "pública",
    "publica",
    "favor",
    "fue",
    "ha",
    "he",
    "realizado",
    "tiene",
    "scjn",
    "suprema",
    "corte",
    "justicia",
    "nación",
    "nacion",
    "unidad",
    "transparencia",
    "amparo",
    "amparos",
    "estados",
    "unidos",
    "ley",
    "federal",
    "código",
    "codigo",
    "reglamento",
    "constitucion",
    "constitución",
    "buenas",
    "tardes",
    "sujeto",
    "obligado",
    "han",
    "sido",
    "¿cual",
    "hacer",
    "llegar",
    "tal",
    "motivo",
    "medio",
    "presente",
    "mexicanos",
    "directo",
    "indirecto",
    "materia",
    "revisión",
    "revision",
    "sentencia",
    "año",
    "semanario",
    "judicial",
    "poder",
    "dirección",
    "general",
    "circuito",
    "número",
    "expediente",
    "es",
    "cual",
    "¿cuállegal",
    "hasta",
    "asuntos",
    "tribunal",
    "sala",
    "año",
    "colegiado",
    "institución",
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("year", type=int, help="Year to analyze")
    # optionals
    parser.add_argument("-n", "--ngram-size", type=int, default=2)
    parser.add_argument("-t", "--top", type=int, default=10)
    parser.add_argument("--filter", type=str, default=None)
    args = parser.parse_args()

    all_text = []
    with open(DEFAULT_CSV, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if int(row["year"]) == args.year:
                text = row.get("DescripcionSolicitud", "").lower()
                # apply filter if there is one provided
                if args.filter:
                    if args.filter.lower() in text:
                        all_text.append(text)
                else:
                    all_text.append(text)

    # clean text, remove punctuation
    full_content = " ".join(all_text)
    for char in ".,?!():;\"'":
        full_content = full_content.replace(char, " ")

    words = full_content.split()
    clean_words = []
    for word in words:
        if word not in STOPWORDS and len(word) > 2:
            clean_words.append(word)

    # count ngrams
    counts = Counter()
    for i in range(len(clean_words) - args.ngram_size + 1):
        ngram = " ".join(clean_words[i : i + args.ngram_size])
        counts[ngram] += 1

    # print ngram results
    print(f"\n Top {args.top} {args.ngram_size}grams for {args.year}")
    if not counts:
        print("No matches found")
    else:
        for gram, count in counts.most_common(args.top):
            print(f"{count} : {gram}")


if __name__ == "__main__":
    main()

# uv run src/analysis/solicitudes/ngrams_solicitudes.py 2024
# uv run src/analysis/solicitudes/ngrams_solicitudes.py 2024 --filter "Zaldivar"
